### ISSUE TITLE
UnicodeEncodeError exception

### ISSUE THREAD

**Issue by serialdoom** [joelthelion/autojump#354]
Im getting this exception when trying to jump to one directory. This is reproducible every time i run autojump.

username@hostname ~ j folder
Traceback (most recent call last):
  File "/home/username/.autojump/bin/autojump", line 385, in <module>
    sys.exit(main(parse_arguments()))
  File "/home/username/.autojump/bin/autojump", line 367, in main
    entries = entriefy(load(config))
  File "/home/username/.autojump/bin/autojump_data.py", line 77, in load
    ifilter(correct_length, imap(parse, f))))
  File "/home/username/.autojump/bin/autojump_data.py", line 67, in <lambda>
    tupleize = lambda x: (x[1], float(x[0]))
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-171: invalid decimal Unicode string
autojump: directory 'folder' not found
Try `autojump --help` for more information.

**Comment by serialdoom** [comment]
I tried to see if there is something wrong with the db file (~/.local/share/autojump/autojump.txt) but nothing seemed wrong in line 171 (i used vim to open the file).
After deleting the database (by accident), the issue went away.
