### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by shivams** [joelthelion/autojump#363]
I am on Mint 17.1 (based on Ubuntu-14.04). Autojump was working just fine until today when it suddenly started showing up error. Now it is not working at all. Every time it shows this error:

```
Traceback (most recent call last):
  File "/usr/bin/autojump", line 513, in <module>
    sys.exit(main())
  File "/usr/bin/autojump", line 459, in main
    config = parse_arg(parse_env(set_defaults()))
  File "/usr/bin/autojump", line 272, in parse_arg
    db = Database(config)
  File "/usr/bin/autojump", line 51, in __init__
    self.load()
  File "/usr/bin/autojump", line 101, in load
    weight, path = line[:-1].split("\t", 1)
ValueError: need more than 1 value to unpack
autojump: directory 'music' not found
Try `autojump --help` for more information.
```

And the thing is it happened very suddenly. I made no change in the system (as far as I can recall). It was like one moment it was working and the other moment it started throwing up this error.

**Comment by shivams** [comment]
Okay. Cracked the issue, guys. Apparently, there was a directory whose name had some special characters in it, including "newline" character. And so, when I checked in the `~/.local/share/autojump/autojump.txt` file, I found that it was in this fashion: (the second directory is the culprit)

```
10 some/nromal/directory
10 the/malicious/directory-!
name
10 another/normal/directory
```

So, its name was overflowing to the next line. 

Now, I had intentionally created this directory to test some of my script (I like to test my scripts for all sorts of weird scenarios including file names containing alien characters). I don't think no user would ever have a directory or file name with newline as a character and so this issue would never occur.

But if there is some way to resolve this, do look at it.

**Comment by shivams** [comment]
A rudimentary method would be to just detect for faulty lines in the `autojump.txt` file and just delete them.
